### ISSUE TITLE
color of label different color to `ui-text`.

### ISSUE THREAD

**Issue by m-schaeffler** [FlowFuse/node-red-dashboard-2-ui-led#6]
### Current Behavior

The label of the LED has a different color then the label of the `ui-text`.

![Bildschirmfoto vom 2024-04-01 19-04-38](https://github.com/FlowFuse/node-red-dashboard-2-ui-led/assets/31366299/9b321553-8d1d-4189-b413-3daa951197ce)

### Expected Behavior

The label of the LED and the label of a `ui-text` shall have the same color.

### Environment

- Node-RED Dashboard 2.0 version: 1.6.1
- Node-RED version: 4.0.0-beta1
- Node.js version:
- Platform/OS: RasperrypiOs
- Browser: Firefox

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by m-schaeffler** [comment]
This is fixed by https://github.com/FlowFuse/node-red-dashboard-2-ui-led/pull/7

**Comment by joepavitt** [comment]
Closed by https://github.com/FlowFuse/node-red-dashboard-2-ui-led/pull/7
