### ISSUE TITLE
Incorrect repo url

### ISSUE THREAD

**Issue by bartbutenaers** [FlowFuse/node-red-dashboard-2-ui-led#9]
Hi guys,

Not sure why this repo is a fork from the example node?  When I try to fork this led repo myself, that fails.  So imho it would be much more understandable if this repo wouldn't be a fork...

In the package json file, the repository [url](https://github.com/FlowFuse/node-red-dashboard-2-ui-led/blob/main/package.json#L11) in incorrect.  So you can't navigate from npm to this repo.  If anybody could change that.

Thanks!
Bart

**Comment by joepavitt** [comment]
Tha ks Bart. Sorry for missing this.

It was a fork because I just used the Example as a starting point, forking was the easiest option at the time.

I'll see if we can reset that so that this improves the developer experience. You should have still been able to fork this repository though.

**Comment by bartbutenaers** [comment]
Thanks guys!!
